### PR TITLE
Preliminary push

### PR DESCRIPTION
**Pull request by yining-sun**
Potential actions to take after consulting Aline:

- Is it advised to use v312 "current contraceptive method" to generate w_CPR?

- Hospitalization not available in hm.dta but exists in ind.dta. Any best practices to specify the data file used for certain countries (I am worried one do-file might draw info from various data files )?

- Hypertention and Diabetes not available in hm.dta, but in ind.dta. Any best practices to specify the data file used for certain countries (I am worried one do-file might draw info from various data files )?

### CODE REVIEW

**Comment by wengxyu1030** [comment]
Dear @yining-sun ,thanks for the questions. 

For the bullet point 2 and 3, where the information is available for a subsect of the household member however the definition of the indicator is for a bigger sample, we decide to not use these limited available data with the consideration of consistency. For the case in hospitalization, hypertension, and diabetes, the indicator is for household members who are over 18 years old, while the information is only available for women/children in ind.dta.  

For the question "Is it advised to use v312 "current contraceptive method" to generate w_CPR?", I will leave it to @Xian152 ,who's positioned to answer this question. 

Dear @Xian152 , could you kindly guide her on this issue on the w_CPR?

**Comment by Xian152** [comment]
@yining-sun 
Hi, as for the hospitalization, Hypertention and Diabetes, yes I agree with Aline. It seems to me that there are no other resources of hospitalization, Hypertention and Diabetes information. 

As for w_CPR, it seems to me that we do have v313 variables for this survey, so I suppose we should use v313, rather than v312, just like what we have done for DHS?

Oooh, looks like that this is also the case for Mozambique2015. Why don't we stick to using v313 to generate w_CPR? @yining-sun @robin-wang @wengxyu1030

**Comment by wengxyu1030** [comment]
Dear @Xian152 , thanks for the confirmation and clarifications. 

Dear @yining-sun ,

For the bullet points 2 and 3, please do not generate the variables Hospitalization, Hypertention, and Diabetes from the limited sample of data. Instead, keep them as missing if the information is missing in the hm.dta. 

For the bullet point 1, please follow @Xian152 's suggestion to use v313 to generate w_CPR.

Cheers, 
Aline

**Comment by yining-sun** [comment]
@wengxyu1030 @robin-wang @Xian152 

Dear all, 

Thanks so much for the comments! I have updated the w_CPR accordingly, uploaded the microdata, and completed the issue #6 . Let me know if you have any other questions. 

Best, 
Yining

**Pull request merged**
