### PR TITLE
Mozambique2015

### PR DESCRIPTION
**Pull request by yining-sun**
- Changed the value label name "M15_1" to run smoothly.

-  Add child_vaccinations country-specific codes

- Add child_illness country-specific codes

- Add sexual_health country-specific codes

Two questions need to consult Aline first:

1. Currently, PNC-related variables are all coded as missing.

However, m70 "baby postnatal check within 2 months", m71 "time after delivery postnatal check took place", m72 "person who performed postnatal checkup" are available in the birth.dta.

But I am not sure if these can be utilized to construct the pnc_any and pnc_eff, as the program logic is a bit different from the reference code in the do-file.

2. Currently, modern contraceptive methods w_CPR is coded as missing. However, in the DHS w_CPR actually exists.

Although no direct question about modern contraceptive methods, in ind.dta, s807b-x listed all the contraceptive methods.

Not sure which categories should be recoded as modern.

### CODE REVIEW

**Comment by wengxyu1030** [comment]
Thanks for your questions @yining-sun . 

As for question 1, I see your point that there's the possibility that we can construct the indicator based on limited available information. However, to keep consistency I will prefer the conservative approach that we put the PNC related indicators on hold for this survey. @Xian152 Please let us know if you have different opinions.

**Comment by wengxyu1030** [comment]
About question 2, thanks for pointing this out. I agree with you @yining-sun that this information is sufficient to generate w_CPR. I am wondering @Xian152 have we ever discussed the list of modern methods? I list the screenshot of the method list for your information. If not let's email Sven to ask his clarification. 
image

**Comment by wengxyu1030** [comment]
Just noted Robin replied the question 2 on issue https://github.com/wengxyu1030/AIS/issues/5#issuecomment-858213623
#5

**Comment by Xian152** [comment]
Hi @yining-sun :
I agree with Aine on Q1, c_pnc_eff and c_pnc_any would be biased if we only base on child pnc information, which is not useful to us.
As for Q2,  I have never looked into the definition of modern methods, as it was defined and given by DHS. Robin shared the definition given by report, which looks informative and convincing to me. So perhaps we could use that definitation. 

As for "Changed the value label name "M15_1"", could you change it back to m15_1 and add a line
```
rename *15_1,lower
```
before the `label value m15 m15_1`. There might be better way to do this, but the real purpose is to make sure this line `label value m15 m15_1` works for all surveys. 

Besides, I saw a vaccine called pcv. I haven't look into the report. Could you tell me what vaccine it is? Thank you.

**Comment by robin-wang** [comment]
Just add a note on modern method of contraception.
Sven's HEFPI introductory materials added that we stick to DHS definitions on what to do. We have not checked very thoroughly on whether this definition might vary by survey

**Comment by yining-sun** [comment]
@wengxyu1030 @robin-wang @Xian152 

Dear all, 

Thanks again for all your comments. 
- w_CPR updated using country-specific conditions based on v313. 
- m15_1 value label changed to lower case
- pcv vaccine: PCV: "PCV Vacina Contra Pneumococos" (AIS12.pdf, pp.xxiiii), in Enligsh, Pneumococcal Vaccine. I also included this information in the issue #5 

Best, 
Yining

**Comment by wengxyu1030** [comment]
Thank you @yining-sun , the code and documentation is clear.

**Pull request merged**
